module.exports = {
    reg_exp: "/^[A-Za-z]+$/",
    reg_exp_space: "/^[A-Za-z ]+$/",
    reg_exp_upper: "/[A-Z]+/",
    table_userpool: "UserPool",
    table_proDealer: "pro_dealer",
    group_superAdmin: "pentair_super_admin_group",
    group_prodealer: "pentair_pro_dealer_group",
    group_dealer: "pentair_dealer_group",
    group_admin: "pentair_admin_group",
    group_home: "pentair_home_user_group",
    table_verification: "verification_code",
    type_home: "pentair_home",
    type_dealer: "pentair_dealer",
    type_admin: "pentair_admin",
    type_prodealer: "pentair_pro_dealer",
    type_superadmin: "pentair_super_admin",
    index_dealer: "d_id-index",
    signup_password: "Password@123"
}